### ISSUE TITLE
predictInterval() breaks with interacted random effects

### ISSUE THREAD

**Issue by sbegueria** [jknowles/merTools#109]
predictInterval() casts an error when a model with interaction in the random effects is used (e.g.: 1 | id:period).

**Comment by jknowles** [comment]
This should work. Can you put together a [reprex](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) so I can investigate this further and see what might be going on?

**Comment by jknowles** [comment]
Closing this because of a lack of reprex. Please reopen if one is created.
