### ISSUE TITLE
Make predictInterval work with large number of sims

### ISSUE THREAD

**Issue by jknowles** [jknowles/merTools#11]
Currently, predictInterval is very RAM-bound when it comes to the number of simulations. On most machines, `n.sims=1000` should work sensibly, even for a model with a reasonably large number of parameters (e.g. ~100). However, increasing the number of sims beyond 1000 will quickly run into RAM limitations for the user. 

There is no reason for this to be the case, as the sims are independent draws from one another. In cases where there are a large number of sims, we should be able to split it into multiple smaller simulation "chunks" and then combine only the predicted `yhat` from these independent simulations in the end. 

We'd need to set up some mechanism to decide when to split, pre-allocate the `yhat` object, and then fill it up in a loop over the chunks to preserve RAM. But, it should be fairly easy.

**Comment by alireza202** [comment]
I get this error when I try to use predictInterval:

>predictInterval(lmer_model, newdata = testing, n.sims = 999, level = 0.99)

> Error: cannot allocate vector of size 3239.1 Gb

My model is not that huge. The data has 14,000 rows, and I have 3 fixed effects, and the formula is:

>y ~ x1 + x2 + x3 + 
>(1 | cat:subcat) +
>(x1 + x2 + x3 || cat)

I tried changing n.sims and level, but I got the same error.

The prediction data set has only 800 rows. Any idea how to fix this issue?

**Comment by jknowles** [comment]
The problem is likely that the original model has a large number of groups in `cat`. Each time you simulate a data set it constructs simulations for all the levels in the original model. Even if the prediction set does not have these levels observed. Do you have something like 2,000 + observed levels of `cat` or especially `cat:subcat`? I'm guessing that's where we're falling down on the job. 

This is a bug of convenience currently as it can be difficult to identify which groups need to be simulated at the top and restrict our simulation to the effect distributions of only the groups which are in the new data.

**Comment by alireza202** [comment]
Thanks for the response. I do have more than 2,000 cat:subcats. Is there any workaround?

**Comment by jknowles** [comment]
No. `predictInterval` will need a patch to restrict the random effect simulation to only values of the grouping terms that appear in `newdata`. You can feel free to fork the function and patch it yourself or to submit a patch via pull request. I won't be able to solve this until later this year or early next calendar year.

**Comment by alireza202** [comment]
I'm trying bootMer, but it's too slow. I'll dig into the predictInterval function to figure out how to do the patch.

**Comment by jknowles** [comment]
You probably need to find a way to subset these two objects in the main simulation loop: 

```
 reMeans <- as.matrix(ranef(merMod)[[j]])
 reMatrix <- attr(ranef(merMod, condVar=TRUE)[[j]], which = "postVar")
```

If you can find a way to subset them by levels only existing in `newData` then it will dramatically reduce the computation time and memory required for the simulation to scale with `newData` and not with the size of the original model.

**Comment by jknowles** [comment]
@alireza202 I'm digging into fixing this bug now because it is bottlenecking some code I want to run in production. Can I ask you -- do you remember what values of `n.sims` you tried? 

It appears I already implemented a procedure to only sim the effects that are observed in `newdata` and now I need to do a loop to chunk out the simulations either by the number of unique random effects to simulate or into "batches" of n.sims. I am trying to decide which to tackle first for users.

**Comment by alireza202** [comment]
I can't remember exactly, but as per my comment above, I tried 999, and lower. My problem was, if I remember correctly, having too many levels. I ended up using Stan for my work, but if you can fix this, it would be great to compare results.

**Comment by jknowles** [comment]
Thanks. 2,000 levels shouldn't have caused a need for a vector of 3290 Gb based on my testing -- how many parameters were there per level (e.g. how many random slopes did you have for each level)? I'm trying to make a reproducible problem that matches yours, but I haven't found a memory allocation that big yet. 

I did already make a few improvements to speed up the code and reduce the memory footprint, but nothing in my testing has caused that problem so I'm just not fitting the right kind of model to figure out where the memory blowup is occurring.

**Comment by alireza202** [comment]
I can't remember exactly, but I was working with a relatively large dataset. I might try it later this month or next, and see if I can reproduce the error.

**Comment by jknowles** [comment]
If you do, give me a heads up. I'm working on some modifications here on GitHub and the dev version should be ready by that time for testing. Thanks!

**Comment by jknowles** [comment]
I believe the current dev version should allow for simulation of prediction intervals using both a large number of parameters and a large number of simulations. I have not found a use case where the `predictInterval` function used more than 8GB of RAM on a reproducible example. The new method works by splitting up the simulation matrix into chunks when the user is asking for either a) a  large number of predicted values in return or b) a large number of simulations per row.
