### ISSUE TITLE
Confidence interval for random effect simulated estimates 

### ISSUE THREAD

**Issue by Dallak** [jknowles/merTools#122]
Hi,
Thank you for the great package!

I like the philosophy behind using simulation for extracting random effect estimates from the posterior of an `lmer` object. Though I'm wonder if it is possible to calculate the CI 95% for the simulated values.

**Comment by jknowles** [comment]
Hi @Dallak 

This should do the trick, just set `level=0.95` when you call `predictInterval`

```
predictInterval(m1, newdata = InstEval[1:10, ], n.sims = 500, level = 0.95, 
                stat = 'median')
```

Or

in `plotREsim` set level to 0.95

```
plotREsim(REsim(m1, n.sims = 100), level = 0.95, stat = 'median', intercept = FALSE)
```

**Comment by Dallak** [comment]
Many thanks for this!
