### ISSUE TITLE
REsim not working

### ISSUE THREAD

**Issue by fcorowe** [jknowles/merTools#125]
Hi,

I am running the example in the R documentation for `REsim` i.e. 

```
require(lme4)
m2 <- lmer(Reaction ~ Days + (Days | Subject), sleepstudy)
re2 <- REsim(m2, 25)
```

and the output is:

```
Error in getMethod("solve", signature(a = "CHMfactor", b = "diagonalMatrix")) : 
  no method found for function 'solve' and signature CHMfactor, diagonalMatrix
```

I ran `showMethods(REsim)`and produced 

```
Function "REsim":
 <not an S4 generic function>
```

Any ideas of what is going wrong and I could fix this issue?

Thanks,
Francisco.

**Comment by russell-ligon** [comment]
Experiencing the same issue.

**Comment by russell-ligon** [comment]
Issue fixed by reinstalling the `arm` package. Perhaps update `merTools` to include dependency checks?

**Comment by jknowles** [comment]
The `arm` package is a strict dependency of `merTools` and should be installed when installing the package. I'm not sure what installation path allows the package to install without the dependency, or it could be an issue with calling the functions from `merTools` without loading the package first. Either way, we are already doing dependency checks. Thanks for the report!
