### ISSUE TITLE
Some methods of binomial specification fail

### ISSUE THREAD

**Issue by jknowles** [jknowles/merTools#18]
The user has multiple ways to specify a binomial outcome and currently predictions only work for one method. 

_from glmer_

``` r
# Specify a two-column vector
## using nAGQ=0 only gets close to the optimum
(gm1a <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd),
               cbpp, binomial, nAGQ = 0))
```

The user can also specify the binomial variable as a probability with the weights vector being used to express the denominator:

``` r
cbpp$obs <- 1:nrow(cbpp)
  d1 <- cbpp
  d1$y <- d1$incidence / d1$size
  gm2 <- glmer(y ~ period +
                  (1 | herd),
                family = binomial, data = d1, nAGQ = 9, weights = d1$size)
```

Finally, the user can specify a factor.

I'm pretty sure the only one we get correct is the last option. There is not a very easy way to detect the `cbind(` construction above, from what I have seen. However, if we could detect it we could do a `stopifnot`. Otherwise this should be described in the documentation. This is on the "nice to have, but not critical" for me.

**Comment by jknowles** [comment]
The latter specification above works, but I'm not sure it would work for new data unobserved by the model...

**Comment by carlbfrederick** [comment]
For the record, can extract the response column(s) from the model.frame with `model.extract(model.frame, component = "response")` or `model.response(model.frame)`

**Comment by carlbfrederick** [comment]
Don't know if this is much of an issue.  The latest version from `predictInterval` (based on pull request #68) does not throw an error for me and returns statistically equivalent predictions to `predict.merMod()`

here are the two examples above and a quick function to compare the fitted values: 

    gm1a <- glmer(cbind(incidence, size - incidence) ~ period + (1 | herd), cbpp, binomial, nAGQ = 0)

    cbpp$obs <- 1:nrow(cbpp)
    d1 <- cbpp
    d1$y <- d1$incidence / d1$size

    gm2 <- glmer(y ~ period +  (1 | herd), family = binomial, data = d1, nAGQ = 9, weights = d1$size)

    myFun <- function(merMod) {
      fake <- predictInterval(merMod)
      fake$reg_predict <- predict(merMod)
      r2 <- summary(lm(fit~reg_predict, data = fake))$adj.r.squared
      out <- fake %>% ggplot(aes(x = reg_predict, y = fit)) + 
        geom_point() + 
        geom_abline(slope = 1, intercept = 0) +
        labs(x = "predict()", y = "predictInterval()", title = paste("Adjusted R2 =", r2))
      return(out)
    }

    myFun(gm1a)

    myFun(gm2)

Am I wrong @jknowles?

**Comment by jknowles** [comment]
Huh. Looks like we did it.

I wonder when that happened. 

Can we write a quick unit test based on your code to make sure we don't unfix it with a future *enhancement* ?

**Comment by carlbfrederick** [comment]
Sure I'll put that on my list ... looking to keep it within some tolerance around the correlation/r2

**Comment by jknowles** [comment]
Yeah -- that sounds good. That's how a lot of the `merPredict` tests are too -- though I need to hard code some real values in there now so that if things move we know it's bad :-)
