### ISSUE TITLE
CRAN Release Rollout

### ISSUE THREAD

**Issue by jknowles** [jknowles/merTools#2]
Here are the remaining to-do items before we try to submit this package to CRAN:

- [x] Fix the NOTES by R CMD CHECK about using `:::`
- [x] Unit tests for the prediction interval function
- [x] Examples for all exported functions
- [x] Additional functions to include for a first release?
- [x] Finish vignette
- [x] Better documentation for all functions that includes a valid results section

**Comment by carlbfrederick** [comment]
*Specific task list*:
 - [ ] Move `shinyMer()` out of release version ... or finish it
 - [ ] Examples to be written:
      - [ ] `FEsim()`
      - [ ] `REextract()`
      - [ ] `REsim()`
      - [ ] `RMSE.merMod()`
      - [ ] `fastdisp()`
      - [ ] `plotFEsim()`
      - [ ] `plotREsim()`
      - [ ] `shinyMer()`

**Comment by jknowles** [comment]
You could tackle the `expectedRank()` change and if you could also do the examples for as many of the above as possible that would be great. 

I will work on the renaming of `groupSim()` and fixing the `shinyMer()` function which I think is critical to release.

**Comment by carlbfrederick** [comment]
great

**Comment by jknowles** [comment]
I think we're pretty darn close to release and these tasks have been covered well.
