### ISSUE TITLE
plotREsim bug

### ISSUE THREAD

**Issue by carlbfrederick** [jknowles/merTools#21]
The labs argument for `plotREsim()`doesn't work as it says it should with multiple random terms per level ... I haven't even tried it with multiple grouping factors and multiple effects.

Also we should change it so that the caterpillar plots are more condensed and user could set the one to order by ... 

... or an even more extravagant fix would be to allow the user to specify the random effect to plot and if more then one are supplied or NULL could do a scatterplot matrix

**Comment by jknowles** [comment]
Ah yes, it does not surprise me there is a massive bug there. Thanks for checking into it. It worked for my dissertation -- which never had multiple terms per level.

**Comment by carlbfrederick** [comment]
Closed via pull request #22
