### ISSUE TITLE
Minor aesthetic bug(s) in plotREsim

### ISSUE THREAD

**Issue by carlbfrederick** [jknowles/merTools#25]
In updating the merToolsIntro vignette, I noticed two aesthetic issues in `plotREsim`

  - [ ] The ordering of different axes is not pretty when different grouping factors use the same level ... the fix for this is straightforward, just have to make the levels we plot by unique
  - [ ] Need to use different highlighting method because when there are 500+ levels of the random effect, the black vs gray distinction is indistinguishable ... perhaps red vs black or ??? ... this tweak is super straightforward

**Comment by jknowles** [comment]
Do you think this is critical for release? If so, we should patch soon. I'm going to try to polish up `shinyMer` today to make it work in more general cases. Then it should almost be ready to go.

**Comment by carlbfrederick** [comment]
It is a little thing, but is bothersome.  I will play around with it some today.

Carl
