### ISSUE TITLE
Output/access predictive simulation values used in predictInterval()

### ISSUE THREAD

**Issue by ulfelder** [jknowles/merTools#30]
The predictInterval() function looks really helpful, but I am also interested in inspecting and visualizing the simulations that would underpin it --- for example, all 1,000 simulated values used in predictInterval(..., n.sims=1000, stat="median", newdata=newdf). If you could add an option that returns a matrix of nrow(newdf) x n.sims dimensions, that would be wonderful.

**Comment by jknowles** [comment]
@ulfelder that should be very easy. How best do you think we should structure this? During the matrix calculation behind `predictInterval` the predictions are broken into the linear prediction for the fixed effect and the linear prediction for the random effect, with each of these stored as a matrix with nrows = number of cases and ncolumns = number of simulations. It's easy enough to combine these and give back a matrix with each row representing a row in the input data and each column representing a simulated yhat. 

Would that work, or would another output format be preferable?

**Comment by ulfelder** [comment]
That would work perfectly. Following Gelman and Hill's text, the arm/sim()-based approach I have been using for models without random effects returns exactly that: a matrix with each row corresponding to the rows in newdata and n.sims columns corresponding to the yhats from the simulations.

**Comment by jknowles** [comment]
@ulfelder if you do this:

```{r}
library(merTools)
 m1 <- lmer(Reaction ~ Days + (1 | Subject), sleepstudy)
preds2 <- predictInterval(m1, newdata = sleepstudy[1:5, ],
                            returnSims = TRUE)
 out <- attr(preds2, "sim.results")
```
The `sim.results` attribute will contain the matrix of predicted yhats as you describe. Let me know if this meets your needs -- it's a good idea to add!

**Comment by ulfelder** [comment]
As Christoph Waltz said in Inglorious Basterds: "Ooohh, that's a bingo!!" Thanks so much!

**Comment by jknowles** [comment]
@ulfelder Glad to help. Please let us know any feedback or problems or improvements. We think it works well for our use cases, but always interested in making it more useful.
