### ISSUE TITLE
Add a function to diagram multilevel models

### ISSUE THREAD

**Issue by jknowles** [jknowles/merTools#37]
Look into the diagrammeR package for parsing models and building model diagrams dynamically.

**Comment by joelgombin** [comment]
This is something I've been meaning to do for quite some time now, if I can be of some help here I'd be glad to.

**Comment by jknowles** [comment]
@joelgombin Are you interested in doing this specifically for multilevel models? I'd be happy to accept a pull request with a function called `diagram` or `diagramPlot` or something like that which spits out a `diagrammeR` object with a model diagram for the `merMod` object. This would be particularly useful within the `shinyMer` function as a sort of landing screen that the user could see the way the model was working. 

Feel free to fork and develop a pull request -- I won't be getting to this for awhile as I am focusing on the imputation functionality for now and some more of the model simulation functions.

**Comment by joelgombin** [comment]
Yes I was interested in doing it for multilevel models. It can be quite complex though in some instances. Do you have any reference in mind with examples of such diagram? 
In my PhD I used diagrams like this one 
![diagram](https://github-cloud.s3.amazonaws.com/assets/1918735/10565099/1ff4d6d0-75c9-11e5-8971-8e016732839c.png), what do you think?

**Comment by jknowles** [comment]
That looks really elegant -- it seems like a great starting point. I had some hand drawn sketches of what I was thinking -- like SEM diagrams -- but this looks good. 

You might want to check out the [semPlot](http://sachaepskamp.com/semPlot) package which was my inspiration for this idea.

**Comment by joelgombin** [comment]
Another possible inspiration would be from the world of Bayesian models, in particular Kruschke: https://github.com/rasmusab/distribution_diagrams

**Comment by jknowles** [comment]
Yeah, I'd definitely like those.
