### ISSUE TITLE
Error with dplyr and predictInterval

### ISSUE THREAD

**Issue by simeond** [jknowles/merTools#38]
I am getting an error using dplyr and predictInterval.  I reckon it is the tbl attribute - as using data.frame works in the example below but not using data_frame.  The error is 
> "Error in `[.data.frame`(tmp, , c(keep, "var"), drop = FALSE) : undefined columns selected"

```
possNames <- expand.grid(letters,LETTERS)
possNames <- paste(possNames[, 1], possNames[, 2])
newFac <- sample(possNames, 32) 

# --- this works ...
modData <- data.frame(
  y = rnorm(500),
  x = rnorm(500),
  team_name = sample(newFac, 500, replace = TRUE)
)

library(merTools)
m0 <- lmer(y ~ x + (1|team_name), data = modData[1:250,])
testPreds <- predictInterval(m0, newdata = modData[251:500,])

# --- this doesnt
library(dplyr)
modData <- data_frame(
  y = rnorm(500),
  x = rnorm(500),
  team_name = sample(newFac, 500, replace = TRUE)
)

m0 <- lmer(y ~ x + (1|team_name), data = modData[1:250,])
testPreds <- predictInterval(m0, newdata = modData[251:500,])
```

**Comment by jknowles** [comment]
I'm not surprised -- `dplyr` does not have consistent behavior within all data.frame operations. 

What's the harm with just doing:

```
newdata <- as.data.frame(newdata)
predictInterval(m0, newdata = newdata)
```

Users of `dplyr` should be used to inconsistent behavior of `tbl` attributes by now.

Do you think `predictInterval` should try to force `newdata` to be a `data.frame` either silently or with a warning to the user?

**Comment by simeond** [comment]
Hi Jared

There's no harm in coercing to data.frame - once you know that is the
issue!

I spent about 3 hours figuring out it was that and not something else, so i
guess anything that helps save someone else that pain.  I would think that
it will be reasonably common as people using dplyr and friends (including
ggplot) will end up using tbl without even knowing.

i reckon forcing it to a data.frame with warning is the best route.

btw.  have really got a lot of value from merTools - so thank you!

simeon

**Comment by jknowles** [comment]
Yes, that makes sense. I'm wondering whether when I coerce I should issue a warning or a message, or issue an error that directs the user to coerce to a data.frame outside of the function. I have to think about which is the most appropriate, but I agree, need to anticipate the dplyr issue and make it clear for the user.

**Comment by carlbfrederick** [comment]
I think we can coerce with a warning. Most people will not mean to pass the 'tbl'. And it wouldn't change the original object.
