### ISSUE TITLE
Fixing Naming

### ISSUE THREAD

**Issue by jknowles** [jknowles/merTools#4]
We need to finalize a number of naming conventions in the package and stabilize function names:

- [x] nsims, nsim, or n.sims? we use the first two, but n.sims is used in the `arm` package
- [x] `wiggleObs` and `averageObs` and `randomObs` could all use better names
- [x] need to set sensible defaults for all functions
- [x] once names are set, need to build examples, etc.

**Comment by carlbfrederick** [comment]
can close pending pull request #26

**Comment by jknowles** [comment]
:clap:
