### ISSUE TITLE
predictIntervals not working

### ISSUE THREAD

**Issue by gmazzochini** [jknowles/merTools#41]
Hello,

I'm trying to run predictInterval function to get the prediction intervals using the same data used to fit the model but getting this error message:

m1<-glmer(cbind(surv,1-surv) ~ treatment*shape + (1|block/treatment/shape) + (1|species), data=dados, family="binomial")

preds <- predictInterval(m1, newdata = dados, n.sims = 10)

> Error in xj[i, , drop = FALSE] : (subscript) logical subscript too long

Any thoughts?

Cheers,
Guilherme

**Comment by jknowles** [comment]
Yes, you cannot specify a glm in the format `cbind(surv, 1-surv)` currently. The way we reconstruct the outcome matrix and build predictions is not compatible with all of the nice ways `lme4` allows for flexible model specification. See #18 . We're open to suggestions on how to fix this, but for now it's an unsupported model specification.

**Comment by gmazzochini** [comment]
Thanks Jared!
No I'm getting this error:

> preds <- predictInterval(m1, newdata = dados, n.sims = 10)
Error in `[.data.frame`(newdata, , j) : undefined columns selected

Solutions?
