### ISSUE TITLE
merTools v 0.2 release

### ISSUE THREAD

**Issue by jknowles** [jknowles/merTools#45]
@carlbfrederick do you have any must-haves either in the existing issues or missing that would be must-have for release? I'm waiting for the maintainer of the `FastGP` package to push his code to CRAN so we can depend on the latest version of that package. Other than that, I think the changes detailed in NEWS merit a new release to CRAN.

**Comment by carlbfrederick** [comment]
No, I think we are good to go with the improved speed.  Then we can attack some of the other issues for a 0.3 release.  My ordered priority list for v0.3 would be: Binomial Specification (#18), User Controlled Case Selection (#32), Imputation (#34), All Term Expected Ranks (#35) and Diagramming (#37).  I think these 5 features would be sufficient to warrant a version upgrade.

**Comment by jknowles** [comment]
Should we fix #47 before we release 0.2? I'm not sure how involved it will be, but I do sense it will be non-trivial.

**Comment by carlbfrederick** [comment]
Perhaps, this does seem like a non-trivial bug for wider-spread adoption. Do you think the key would be to figure out how *lmer functions parse this specification?

**Comment by jknowles** [comment]
We don't really parse the formula for the random effects except to make a model matrix so our problem is either that the model matrix does not line up with the random effects, or the functions we use to extract the random effect means or the var-cov matrix is wrong. If it's the model matrix we build, that is an easy fix. If it is a problem in extracting the correct var-cov matrix, then I think it could get tough.

**Comment by jknowles** [comment]
I think I have #47 fixed and #46 is a quick fix. I'd like to fix #48 (nested models don't work with the draw functions) as well before we release. Then I would say we should be able to save the rest for the next release. I'm really scared by #18 about binomial methods -- I think it might require refactoring the whole way we parse formulas and construct model frames. 

@carlbfrederick Mind taking a look at the dev branch and seeing if you find any problems? I tweaked some tests, but I think the new method is doing what we hoped and not changing anything like messing up the ordering of effects or giving inaccurate predictions.

**Comment by jknowles** [comment]
One possible issue I have found is that confidence intervals seem to be a little to a lot wider on some binomial models than they were before. Problem is, I'm not sure if this is right, or if these are just poorly fitting models.
