### ISSUE TITLE
predictInterval cannot handle nested effect specifications

### ISSUE THREAD

**Issue by jknowles** [jknowles/merTools#47]
[From this discussion on CrossValidated](http://stats.stackexchange.com/questions/147836/prediction-interval-for-lmer-mixed-effects-model-in-r/167059?noredirect=1#comment368120_167059)

````r
  library(ggplot2)
  library(lme4)
  library(merTools)
  mod1 <- lmer(sleep_total ~ bodywt + (1|vore/order), data=msleep)
  msleep$combn <- paste(msleep$vore, msleep$order, sep = "__")
  mod2 <- lmer(sleep_total ~ bodywt +  (1|combn) + (1|vore), data=msleep)
  predInt <- predictInterval(merMod=mod1, newdata=msleep)
  predInt <- predictInterval(merMod=mod2, newdata=msleep)
````

The first specification does not work, but the identical second specification does. We should make the function support nested specifications.

**Comment by tjmahr** [comment]
[Related issue](https://stackoverflow.com/questions/35188893/problems-simulating-effects-with-mertools) for `draw`.

**Comment by jknowles** [comment]
The problem with this is that `formulaBuild` is not parsing the interaction correctly for nested effects. This is due to how it creates a model matrix that includes all fixed and random slopes and intercepts. I think if I modify the way it parses the formula in lme4 this should work.

**Comment by jknowles** [comment]
This is fixed now.
