### ISSUE TITLE
New sampler leads to wider confidence intervals

### ISSUE THREAD

**Issue by jknowles** [jknowles/merTools#49]
Changing over the multivariate normal sampler has led to consistently wider confidence intervals for some test problems -- notably the GLMM in the vignette using the `VerbAgg` data. Looking at new versions of this vignette and old versions it is clear that switching to `FastGP` has resulted in consistently wider confidence intervals due to wider variance in the sampled values of the random effects. 

I do not know whether to call this a feature or a bug. Were the intervals too narrow before? I do not have a good simulated example to target so I'm not sure how to proceed in either a) reverting back to the slightly slower `mvtnorm`, or b) documenting this possibility and advising users to set level more conservatively in `predictInterval`. 

@carlbfrederick Thoughts?

**Comment by carlbfrederick** [comment]
This is certainly something that should be pinned down.  My gut reaction is that it is better to err on the side of wider intervals. Does `FastGP` help with our memory issues or just increase speed?.  If it is just a speed thing, I think we should hold off and keep `mvtnorm` (are there any existing comparisons between the two already?) until we can make an informed decision about which is more correct.

If it helps the memory thing then I say keep `FastGP`, make a note about the change in the News and possibly in the help documentation about the change. Again, making CIs artificially wider seems better than artificially narrower.

**Comment by jknowles** [comment]
@carlbfrederick `FastGP` just helps with speed -- I do not think there are any implications for memory. It is about 10% faster in some cases, in other cases more like 1-2%. I was going to code up a simulation to see if I can pin down when and why `FastGP` and `mvtnorm` differ (even in cases of a big number of samples). I think it has something to do with how they handle the case where the sigma matrix contains values very close to 0 -- but that is just a hunch. 

I am leaning toward reverting back to `mvtnorm` and seeing what that looks like as well. But I will write up a test of the two and compare them to see what might be going on. I'll report back.

I think I've fixed everything else including the nested grouping terms.

**Comment by carlbfrederick** [comment]
Awesome.
