### ISSUE TITLE
predictInterval ordering problem

### ISSUE THREAD

**Issue by fbaluch** [jknowles/merTools#54]
There seems to be some issue when there are more than 1000 rows or .parallel=TRUE for some datasets. Also it seems like there is an issue when data has row.names that don't match the order of the rows, but I am unable to create a small example. 

p_interval_1000 = predictInterval(mix,newdata=train_sel[1:1000,], n.sims=999) [produces correct ordering]
p_interval_1001 = predictInterval(mix,newdata=(train_sel[1:1001,]),n.sims=999) [produces incorrect ordering]
p_interval_parallel_1000 = predictInterval(mix,newdata=train_sel[1:1000,],.parallel=TRUE,n.sims=999) [produces incorrect ordering]

> p_interval_1000[1:2,]
        fit       upr       lwr
1 -4.997413 -3.467581 -6.477477
2 -5.080779 -3.572478 -6.623902
> p_interval_1001[1:2,]
         fit      upr       lwr
1 -0.1146402 1.449350 -1.661104
2 -0.1988615 1.266367 -1.684106
> p_interval_parallel_1000[1:2,]
          fit      upr       lwr
1 -0.08189119 1.399394 -1.606625
2 -0.23888845 1.341094 -1.715493

**Comment by carlbfrederick** [comment]
Thanks for the heads up.  Our typical use case is far fewer than 1000 observations, so we may have never run into this issue. Your explanation makes sense.  Could you say a bit more about the type of model you encountered this error on?  

  - What is the structure of your (g)lmer call?
  - Approximate number of levels associated with each random factor?
  - Any other potentially pertinent details?

Not sure what information will be necessary, but having this information will allow me to build a big example to see if I can replicate the issue.

**Comment by carlbfrederick** [comment]
Turns out it wasn't an ordering issue, but an issue with our code to utilize multiple processors with large simulation data sets (`newdata`) or otherwise using `parallel=TRUE`.  We had included an option to pass further specifications to the foreach call (`.paropts`) but this was causing the result to be NULL. Thus, in practice we weren't including any random effects for predictions with a sample size of 1001 or greater and/or calls to parallel.

It wasn't an ordering issue but another error.  I will push a patch up later today and will test the bug fixes before updating the package here and on CRAN.

**Comment by fbaluch** [comment]
Sorry I couldn't be of more help during this time but it appears you didn't
need it :). Thanks for putting in the fix Carl!

On Wed, Jul 6, 2016 at 6:58 AM, Carl Frederick <notifications@github.com>
wrote:

> Turns out it wasn't an ordering issue, but an issue with our code to
> utilize multiple processors with large simulation data sets (newdata) or
> otherwise using parallel=TRUE. We had included an option to pass further
> specifications to the foreach call (.paropts) but this was causing the
> result to be NULL. Thus, in practice we weren't including any random
> effects for predictions with a sample size of 1001 or greater and/or calls
> to parallel.
>
> It wasn't an ordering issue but another error. I will push a patch up
> later today and will test the bug fixes before updating the package here
> and on CRAN.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jknowles/merTools/issues/54#issuecomment-230779382>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEy7fJxtQmGMkXb9172k3UOWwXb5zKkZks5qS7SZgaJpZM4I-ZcF>
> .
>



-- 
Farhan Baluch, Ph.D.,
www.farhanbaluch.com

**Comment by carlbfrederick** [comment]
closed by branch Issue53
