### ISSUE TITLE
predictInterval for glmer.nb

### ISSUE THREAD

**Issue by alireza202** [jknowles/merTools#57]
Is it possible to get prediction intervals for glmer.nb models? I get this warning:

```
In predictInterval(merMod = fit_model, newdata = testing):    Prediction for NLMMs or GLMMs 
that are not mixed binomial regressions is not tested. Sigma set at 1
```

**Comment by jknowles** [comment]
I do not believe negative bionomial models are supported at this time. There is some question about the appropriate handling of the random effect structure. Sorry!
