### ISSUE TITLE
plotFEsim warning duplicated factors

### ISSUE THREAD

**Issue by danprec** [jknowles/merTools#58]
Hi, 

Whenever I try to use plotFEsim, I get the following warning message, and the plot is not produced:

```
Warning messages:
1: In `levels<-`(`*tmp*`, value = if (nl == nL) as.character(labels) else paste0(labels,  :
  duplicated levels in factors are deprecated 
```

I tried to modify a bit the ggplot part of the function to get around that, and realized that the plot is produced fine if `data$term <- factor(data$term)` is used, instead of the original form with the `levels=...` command. Also, calling on the original factor command alone (To check the output), it generates a list where it seems that the factor's levels are repeated 5x

**Comment by jknowles** [comment]
Without a reproducible example we won't be able to recreate or diagnose this problem. If you could send along a minimal dataset and syntax that generates this error, we can look into it.

**Comment by jknowles** [comment]
Without a reproducible example I have not been able to recreate this error so I am going to close it.
