### ISSUE TITLE
predictInterval: Don't require ranef's in newdata

### ISSUE THREAD

**Issue by ashenkin** [jknowles/merTools#60]
Hi Jared,

Thanks for this cool package.  I've also pointed a number of students to your r bootcamp stuff in the past as well - much appreciated.

For predictInterval, would it be possible to not require random effects in newdata?  I usually apply random effects to factors in which I don't have specific interest in predicting.  Thus, having the interval incorporate random effect variation, but not predict for a specific level of random effect (i.e. 0), would be desirable.  Hope this makes sense.  Thanks!

**Comment by jknowles** [comment]
Off the top of my head I would do this by setting the value of the random effect in the newdata object to be the value of the grouping factor that is associated with a 0 effect. You can use the `averageObs` function to identify what this value is and then you can set this value in `newdata` and this will be equivalent to what you want. 

Why you can't just leave off the variable in `newdata` is that `predictInterval` relies on the correct number of columns being in place to do the mechanics of prediction. Omitting a variable would then force us to do a lot of extra computations to identify what we should substitute in. 

We are looking at an option that produces intervals with just the fixed component. I am not sure when that work will be completed, but you could also use the standard `lme4` predict in this case.

**Comment by ashenkin** [comment]
Thanks Jared.  First, yes, a change like this would involve substantial 
work I imagine.

lme4.predict, with re.form = NA, just sets the random effects to 0, and 
as you know, doesn't produce intervals.  What would be of interest, 
however, would be sampling across the random effect levels when 
constructing the confidence interval.  Perhaps random effect variation 
is already included in the interval estimate?  If so, then yes, just 
having an argument that would do that averageObs calculation internally 
would solve it.

Thanks,
Allie

**Comment by CJustice77** [comment]
Hi there. I agree with Allie's comment and I'm wondering if any advances have been in merTools yet that allow users to simply zero out some or all of the random effects as Allie suggested. I attempted to use averageObs function as well as draw function to obtain the average values for random effect factors, but I received an error message for both. This may be due to the fact that my random effects are nested. Any help would be appreciated.

Casey

**Comment by jknowles** [comment]
This functionality is enabled by using `predictInterval(merMod, ... , which = "fixed")` which will return the variation only for the fixed effects and the model residual variance (the equivalent of selecting the average term for the random effects, centered at 0).

**Comment by ericgtaylor** [comment]
FWIW, which = "fixed" still requires the group variable. 
```
Error in model.frame.default(tt, newdata.NA, na.action = na.pass) : 
  invalid type (closure) for variable 'id'
```
