### ISSUE TITLE
varList does not like ==

### ISSUE THREAD

**Issue by jknowles** [jknowles/merTools#61]
The way `varList` specifies things to subset the data does not fail when the user does things wrong:

This is how a user should do this:

```
draw(fm1, type = "average", varList = list("Subject" = "308"))
```
But, if the user makes the slight error of using the normal logical test, instead of the assignment operator and types:

```
draw(fm1, type = "average", varList = list("Subject" == "308"))
```

`draw` does not fail, but instead returns a subset from the entire dataset. It should either issue a warning or an error so that users are not confused, or it should silently do the substitution so both specifications are acceptable.

**Comment by carlbfrederick** [comment]
It should probably noisily do the substitution (at least once), so that people don't accidentally run newer code on older versions some how.
