### ISSUE TITLE
Add a comparison to rstanarm in the vignette

### ISSUE THREAD

**Issue by jknowles** [jknowles/merTools#64]
What do our prediction intervals look like compared to the predictions produced by `posterior_predict` in the `rstanarm` package? This would be good to add to the vignette for comparison sake for users.

**Comment by carlbfrederick** [comment]
I was thinking about bringing in/referencing the rstanarm package in some way too.  Hopefully ours will be between lme4 and rstanarm.  I should have some time to play with this during the long weekend here, but if you want to tackle it sooner, feel free.

**Comment by jknowles** [comment]
Just started checking it out and playing with it on another branch -- 'stanarm-comparison`. I probably won't make much more progress on it until another week or so, so see what you come up with and lets compare notes after we've both taken a look.

**Comment by carlbfrederick** [comment]
Cool.
