### ISSUE TITLE
Error: class(merMod) %in% c(“lmerMod”,...

### ISSUE THREAD

**Issue by pablobernabeu** [jknowles/merTools#65]
`library(merTools)` has suddenly stopped working for me. While inputting a right `lmer` model into `plotFEsim(FEsim(m0.1))`, I get this error:

    Error: class(merMod) %in% c("lmerMod", "glmerMod", "blmerMod", "bglmerMod") is not TRUE

*I want to underline that the model inputted is right, so an example environment wouldn't help too much here. For reproduction, any `lmer` model with a couple of random and fixed effects should do.*

Thank you so much for your attention.

**Comment by jknowles** [comment]
What version are you using of both lme4 and merTools?

**Comment by pablobernabeu** [comment]
Well, I just re-installed merTools and it works again! Sorry for
disturbing, and thank you for your quick response.

**Comment by jknowles** [comment]
Thanks for taking the time to report. `merTools` is a work in progress and feedback from users like you @pablobernabeu helps us make sure it works for all the many edge cases people use `lme4` models for!
